[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="user" type="String" --]
[#-- @ftlvariable name="user.username" type="String" --]
[#-- @ftlvariable name="user.email" type="String" --]
[#-- @ftlvariable name="usernameError" type="String" --]
[#-- @ftlvariable name="passwordError" type="String" --]
[#-- @ftlvariable name="password2Error" type="String" --]
[#-- @ftlvariable name="emailError" type="String" --]
[#-- @ftlvariable name="message" type="String" --]
[#-- @ftlvariable name="filter" type="String" --]
[#-- @ftlvariable name="_csrf.token" type="java.lang.String" --]